# Generated by Django 2.0.4 on 2018-07-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, null=True)),
                ('filename', models.CharField(max_length=50, null=True)),
                ('querytime', models.DateTimeField(null=True)),
            ],
        ),
    ]
